apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-sql
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/crossplane-tutorial
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational PostgreSQL databases in AWS.
    meta.crossplane.io/readme: A Configuration package that defines a SQL and SQLClaim types that can be used to create and provision fully operational databases in AWS.
spec:
  crossplane:
    version: ">=v1.14.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v1.0.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-rds
      version: ">=v1.0.0"
